//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePft
    {
        public int EmployeePftId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> PftTypeId { get; set; }
        public Nullable<int> PftResultId { get; set; }
        public System.DateTime PftDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual PftResult PftResult { get; set; }
        public virtual PftType PftType { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
