//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTraining
    {
        public int EmployeTrainingId { get; set; }
        public int TrainingPlanId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
    }
}
