//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeFamilyPermission
    {
        public int EmployeeFamilyPermissionId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> RankId { get; set; }
        public Nullable<int> RelationId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string RelativeName { get; set; }
        public string VisitPurpose { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Rank Rank { get; set; }
        public virtual Relation Relation { get; set; }
    }
}
