//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MissionAppBranch
    {
        public int MissionAppBranchId { get; set; }
        public int MissionAppointmentId { get; set; }
        public int BranchId { get; set; }
    
        public virtual MissionAppointment MissionAppointment { get; set; }
        public virtual Branch Branch { get; set; }
    }
}
