//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Office()
        {
            this.Achievement = new HashSet<Achievement>();
            this.EmployeeOpr = new HashSet<EmployeeOpr>();
            this.EmployeeOpr1 = new HashSet<EmployeeOpr>();
            this.EmployeeTransferFuturePlan = new HashSet<EmployeeTransferFuturePlan>();
            this.ExtraAppointment = new HashSet<ExtraAppointment>();
            this.OfficeAppointment = new HashSet<OfficeAppointment>();
            this.ProposalDetail = new HashSet<ProposalDetail>();
            this.Transfer = new HashSet<Transfer>();
        }
    
        public int OfficeId { get; set; }
        public string Name { get; set; }
        public string NameBangla { get; set; }
        public string ShortName { get; set; }
        public string ShortNameBangla { get; set; }
        public string SecurityName { get; set; }
        public Nullable<int> PatternId { get; set; }
        public Nullable<int> ShipCategoryId { get; set; }
        public Nullable<int> ShipType { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> ShipOriginId { get; set; }
        public string AddressInfo { get; set; }
        public Nullable<int> BornOfficeId { get; set; }
        public bool BornOffice { get; set; }
        public bool Establishment { get; set; }
        public bool GovtApproved { get; set; }
        public bool CoastGuard { get; set; }
        public bool IsOutsideOrg { get; set; }
        public int ObjType { get; set; }
        public bool IndCmd { get; set; }
        public bool SeaServiceCnt { get; set; }
        public bool IsDocyardCount { get; set; }
        public bool IsIsoCount { get; set; }
        public bool IsDeputationCount { get; set; }
        public bool IsIntelligenceServiceCount { get; set; }
        public bool CmdService { get; set; }
        public bool Commissioned { get; set; }
        public Nullable<System.DateTime> CommDate { get; set; }
        public string CommissionBy { get; set; }
        public bool DeCommissioned { get; set; }
        public Nullable<System.DateTime> DeComDate { get; set; }
        public string DeComPurpose { get; set; }
        public int ParentId { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public Nullable<int> AdminAuthorityId { get; set; }
        public Nullable<System.DateTime> SeServStartDate { get; set; }
        public Nullable<System.DateTime> SeServEndDate { get; set; }
        public Nullable<System.DateTime> CommandServStartDate { get; set; }
        public Nullable<System.DateTime> CommandServEndDate { get; set; }
        public bool IsMoved { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> OPatCd { get; set; }
        public Nullable<int> OrgCd { get; set; }
        public bool IsSubmarineCount { get; set; }
        public Nullable<bool> ActiveStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Achievement> Achievement { get; set; }
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeOpr> EmployeeOpr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeOpr> EmployeeOpr1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeTransferFuturePlan> EmployeeTransferFuturePlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtraAppointment> ExtraAppointment { get; set; }
        public virtual Pattern Pattern { get; set; }
        public virtual ShipCategory ShipCategory { get; set; }
        public virtual Zone Zone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeAppointment> OfficeAppointment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProposalDetail> ProposalDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transfer> Transfer { get; set; }
    }
}
