//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OprGrading
    {
        public int Id { get; set; }
        public double MinGrade { get; set; }
        public double MaxGrade { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
    }
}
