//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchColumn
    {
        public int Id { get; set; }
        public string Label { get; set; }
        public string ColumnName { get; set; }
        public string UserId { get; set; }
        public bool IsSelected { get; set; }
    }
}
