//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeaService
    {
        public int SeaServiceId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> ShipType { get; set; }
        public string ShipName { get; set; }
        public string OrganizationName { get; set; }
        public string AppointmentName { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Purpose { get; set; }
        public string Reference { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
