//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceExam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceExam()
        {
            this.EmployeeServiceExamResult = new HashSet<EmployeeServiceExamResult>();
        }
    
        public int ServiceExamId { get; set; }
        public int ServiceExamCategoryId { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public int BranchId { get; set; }
        public int NOS { get; set; }
        public byte AttTime { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ServiceExamCategory ServiceExamCategory { get; set; }
        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeServiceExamResult> EmployeeServiceExamResult { get; set; }
    }
}
