//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpouseForeignVisit
    {
        public int SpouseForeignVisitId { get; set; }
        public int SpouseId { get; set; }
        public int CountryId { get; set; }
        public string Purpose { get; set; }
        public string AccompaniedBy { get; set; }
        public Nullable<System.DateTime> StayFromDate { get; set; }
        public Nullable<System.DateTime> StayToDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Spouse Spouse { get; set; }
    }
}
