//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTransfer
    {
        public int TransferId { get; set; }
        public Nullable<int> TransferFor { get; set; }
        public int EmployeeId { get; set; }
        public int TransferMode { get; set; }
        public bool isActive { get; set; }
        public Nullable<int> CurrentBornOfficeId { get; set; }
        public Nullable<int> AttachOfficeId { get; set; }
        public Nullable<int> EmployeeStatus { get; set; }
        public string TransferModeName { get; set; }
        public string BornOffice { get; set; }
        public string CurrentAttach { get; set; }
        public string Appointment { get; set; }
        public System.DateTime FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string FileName { get; set; }
        public Nullable<int> AppointmentCategoryId { get; set; }
        public Nullable<int> AppointmentNatureId { get; set; }
        public string FullAppointment { get; set; }
        public string Duration { get; set; }
        public string Billet { get; set; }
        public string Reason { get; set; }
        public string Rank { get; set; }
        public string Country { get; set; }
        public Nullable<int> CountryId { get; set; }
        public int TranferType { get; set; }
        public Nullable<int> AppointmentId { get; set; }
        public Nullable<bool> IsInstrServiceCount { get; set; }
    }
}
