using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Infinity.Bnois.Api.Right
{
    /// <summary>
    /// 
    /// </summary>
    public static class MASTER_SETUP
    {
        public const int RANKS = 1001;
        public const int RANKS_CATEGORIES = 1002;
        public const int UPAZILAS = 1003;
        public const int TERMINATION_TYPES = 1004;
        public const int SUBJECTS = 1005;
        public const int SUB_CATEGORIES = 1006;
        public const int SUB_BRANCHES = 1007;
        public const int STREAMS = 1008;
        public const int SERVICE_EXTENSIONS = 1009;
        public const int RETIRED_AGES = 1010;
        public const int RELIGIONS = 1011;
        public const int PHYSICAL_STRUCTURES = 1012;
        public const int MEDICAL_CATEGORIES = 1013;
        public const int MARITAL_TYPES = 1014;
        public const int LEAVE_TYPES = 1015;
        public const int LEAVE_POLICIES = 1016;
        public const int LEAVE_ENTRIES = 1017;
        public const int INSTITUTE_TYPES = 1018;
        public const int INSTITUES = 1019;
        public const int EYE_VISIONS = 1020;
        public const int EXAMINATION_CATEGORIES = 1021;
        public const int EXAMINATION = 1022;
        public const int DIVISIONS = 1023;
        public const int DISTRICTS = 1024;
        public const int COUNTRIES = 1025;
        public const int COMMISION_TYPES = 1026;
        public const int COLORS = 1027;
        public const int CATEGORIES = 1028;
        public const int BRANCHES = 1029;
        public const int BOARDS = 1030;
        public const int BLOOD_GROUPS = 1031;
        public const int BATCHES = 1032;
        public const int AGE_SERVICE_POLICIES = 1033;
        public const int COURSE_CATEGORIES = 1034;
        public const int COURSE_SUB_CATEGORIES = 1035;
        public const int EMP_RUN_MISSINGS = 1036;
        public const int EMP_REJOINS = 1037;
        public const int RESULT_TYPES = 1038;
        public const int COURSES = 1039;
        public const int TRAINING_INSTITUTES = 1040;
        public const int TRAINING_PLANS = 1041;
        public const int TRAINING_RESULTS = 1041;
        public const int EXTRACURRICULAR_TYPES = 1042;
        public const int RELEGION_CAST = 1043;
        public const int PARENTS = 1044;
        public const int OCCUPATIONS = 1045;
        public const int PRE_COMMISSION_RANKS = 1046;
        public const int RELATIONS = 1049;
        public const int HEIR_TYPES = 1050;
        public const int APPOINTMENT_CATEGORIES = 1051;
        public const int APPOINTMENT_NATURE = 1052;
        public const int PATTERN = 1053;
        public const int ZONES = 1054;
        public const int SHIP_CATEGORIES = 1055;
        public const int PROMOTION_BOARDS = 1056;
        public const int OFFICES = 1057;
		public const int LPRCALCULATEINFO = 1058;
        public const int EXECUTION_REMARKS = 1059;
        public const int PROMOTION_NOMINATIONS = 1060;
        public const int MEDALS = 1061;
        public const int MEMBER_ROLES = 1062;
        public const int AWARDS = 1063;
        public const int PUBLICATION_CATEGORIES = 1064;
        public const int PUBLICATIONS = 1065;
        public const int BOARD_MEMBERS = 1066;
        public const int PUNISHMENT_CATEGORIES = 1067;
        public const int PUNISHMENT_SUB_CATEGORIES = 1068;
        public const int COMMENDATIONS = 1069;
        public const int PROMOTION_EXECUTIONS = 1070;
        public const int PUNISHMENT_NATURES = 1071;
        public const int ACHIEVEMENTS = 1072;
        public const int EMPLOYEE_LPR = 1073;
        public const int MEDAL_AWARDS = 1074;
        public const int OBSERVATION_INTELLIGENT_REPORTS = 1075;
        public const int PUNISHMENT_ACCIDENTS = 1076;
        public const int LEAVE_BREAK_DOWN = 1077;
        public const int NOMINATIONS = 1078;
        public const int OFFICER_TRANSFERS = 1079;
        public const int NOMINATION_SCHEDULES = 1080;
        public const int VISIT_CATEGORIES = 1081;
        public const int VISIT_SUB_CATEGORIES = 1082;
        public const int MISSION_APPOINTMENTS = 1083;
        public const int SPORTS = 1084;
        public const int EMPLOYEE_SECURTIY_CLEARANCES = 1085;
        public const int SERVICE_EXAM_CATEGORIES = 1086;
        public const int SERVICE_EXAMS = 1087;
        public const int EMPLOYEE_SERVICE_EXAM_RESULTS = 1088;
        public const int EMPLOYEE_PFTS = 1089;
	    public const int LEAVE_PURPOSE = 1090;
	    public const int CURRENT_STATUS = 1091;
	    public const int EXAM_SUBJECTS = 1092;
        public const int PROMOTION_POLICIES = 1093;
        public const int TRACE_SETTINGS = 1094;
        public const int OPR_Entries = 1095;
        public const int SEA_SERVICES = 1096;
        public const int EMPLOYEE_COURSE_FUTURE_PLANS = 1097;
        public const int EMPLOYEE_TRANSFER_FUTURE_PLANS = 1098;
        public const int CERTIFICATES = 1099;
        public const int EMPLOYEE_REPORTS = 1100;
        public const int TRANSFER_PROPOSALS = 1101;
        public const int PROPOSAL_DETAILS = 1102;
        public const int ADVANCE_SEARCH = 1103;
        public const int BASIC_SEARCH = 1104;
        public const int RESULT_GRADES = 1105;
        public const int SHIP_MOVEMENT = 1106;
        public const int DAILY_PROCESSES = 1107;
        public const int STATUS_CHANGES = 1108;
        public const int EXTRA_APPOINTMENTS = 1109;
        public const int REMARKS = 1110;
        public const int FOREIGN_PPROJECTS = 1111;
        public const int EMPLOYEES = 1112;
        public const int NATIONALITY = 1113;
        public const int RETIRED_EMPLOYEE = 1114;
        public const int DASHBOARD = 1115;
        public const int QUICK_LINKS = 1116;
        public const int MODULES = 1117;
        public const int FEATURES = 1118;
        public const int ROLES = 1119;
        public const int USERS = 1120;
        public const int SPECIAL_APT_TYPES = 1121;
        public const int EMPLOYEE_HAJJ_DETAILS = 1122;
        public const int EVIDENCES = 1123;
        public const int EMPLOYEE_CAR_LOAN = 1124;
        public const int EMPLOYEE_FAMILY_PERMISSION = 1125;
        public const int CAR_LOAN_FISCAL_YEAR = 1126;
        //public const int EMPLOYEE_CAREER_FORECAST = 1127;
        public const int MSC_INSTITUTE = 1128;
        public const int MSC_PERMISSION_TYPE = 1129;
        public const int EMPLOYEE_MSC_EDUCATION = 1130;
        public const int MSC_EDUCATION_TYPE = 1131;
        public const int CAREER_FORECAST_SETTING = 1132;
        public const int CAREER_FORECAST = 1133;
        public const int BNOIS_LOG_INFO = 1134;
        public const int EMPLOYEE_COXO_SERVICE = 1135;
        public const int ROASTER_LIST = 1136;
        public const int TOEAUTHORIZED = 1137;
        public const int OODENTRY = 1138;
        public const int TOEOSENTRY = 1139;
        public const int EMPLOYEE_UNM_DEFERMENT = 1140;
        public const int CO_FF_RECOM = 1141;
        public const int MINUITE = 1142;
        public const int ROASTER_LIST_EOSOLO = 1143;
    }
}
