//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AddressId { get; set; }
        public int EmployeeId { get; set; }
        public int AddressType { get; set; }
        public string CareOf { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> UpazilaId { get; set; }
        public string AddressDetailBangla { get; set; }
        public string AddressDetailEnglish { get; set; }
        public string EmailAddress { get; set; }
        public string Phone { get; set; }
        public string PostOfficeName { get; set; }
        public string PostCode { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual District District { get; set; }
        public virtual Division Division { get; set; }
        public virtual Upazila Upazila { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
