//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AptCat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AptCat()
        {
            this.MissionAppointments = new HashSet<MissionAppointment>();
            this.EmployeeTransferFuturePlan = new HashSet<EmployeeTransferFuturePlan>();
            this.OfficeAppointment = new HashSet<OfficeAppointment>();
        }
    
        public int AcatId { get; set; }
        public int ANatId { get; set; }
        public string AcatNm { get; set; }
        public string AcatNmBng { get; set; }
        public string ACatShNm { get; set; }
        public string ACatShNmBng { get; set; }
        public bool GoAcr { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MissionAppointment> MissionAppointments { get; set; }
        public virtual AptNat AptNat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeTransferFuturePlan> EmployeeTransferFuturePlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeAppointment> OfficeAppointment { get; set; }
    }
}
