//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoardMember
    {
        public int BoardMemberId { get; set; }
        public int PromotionBoardId { get; set; }
        public int EmployeeId { get; set; }
        public int MemberRoleId { get; set; }
        public bool IsVoteAllowed { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual MemberRole MemberRole { get; set; }
        public virtual PromotionBoard PromotionBoard { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
