//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonusPtMedal
    {
        public int BonusPtMedalId { get; set; }
        public int TraceSettingId { get; set; }
        public int MedalId { get; set; }
        public Nullable<double> Point { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual TraceSetting TraceSetting { get; set; }
        public virtual Medal Medal { get; set; }
    }
}
