//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branch()
        {
            this.MissionAppBranch = new HashSet<MissionAppBranch>();
            this.OfficeAppBranch = new HashSet<OfficeAppBranch>();
            this.ServiceExam = new HashSet<ServiceExam>();
            this.TrainingBranch = new HashSet<TrainingBranch>();
            this.EmployeeServiceExt = new HashSet<EmployeeServiceExt>();
            this.EmpRunMissings = new HashSet<EmpRunMissing>();
            this.BraCtryCoursePoints = new HashSet<BraCtryCoursePoint>();
            this.CareerForecastSetting = new HashSet<CareerForecastSetting>();
            this.EmployeeGeneral = new HashSet<EmployeeGeneral>();
            this.ToeAuthorized = new HashSet<ToeAuthorized>();
            this.DashBoardBranchByAdminAuthority700 = new HashSet<DashBoardBranchByAdminAuthority700>();
        }
    
        public int BranchId { get; set; }
        public string Name { get; set; }
        public string NameBan { get; set; }
        public string ShortNameBan { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Description { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MissionAppBranch> MissionAppBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeAppBranch> OfficeAppBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceExam> ServiceExam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingBranch> TrainingBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeServiceExt> EmployeeServiceExt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpRunMissing> EmpRunMissings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BraCtryCoursePoint> BraCtryCoursePoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareerForecastSetting> CareerForecastSetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeGeneral> EmployeeGeneral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToeAuthorized> ToeAuthorized { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashBoardBranchByAdminAuthority700> DashBoardBranchByAdminAuthority700 { get; set; }
    }
}
