//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.TrainingPlans = new HashSet<TrainingPlan>();
            this.EmployeeCourseFuturePlan = new HashSet<EmployeeCourseFuturePlan>();
        }
    
        public int CourseId { get; set; }
        public int CourseCategoryId { get; set; }
        public int CourseSubCategoryId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string FullName { get; set; }
        public string ShortName { get; set; }
        public string NameInBangla { get; set; }
        public Nullable<int> Priority { get; set; }
        public bool ANGF { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public bool SplQualification { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual CourseCategory CourseCategory { get; set; }
        public virtual CourseSubCategory CourseSubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingPlan> TrainingPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeCourseFuturePlan> EmployeeCourseFuturePlan { get; set; }
    }
}
