//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoXoService
    {
        public int CoXoServiceId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public Nullable<int> Type { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Appointment { get; set; }
        public Nullable<int> ShipType { get; set; }
        public Nullable<System.DateTime> ProposedDate { get; set; }
        public Nullable<int> CompleteStatus { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Office Office { get; set; }
    }
}
