//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashBoardMinuite110
    {
        public int MinuiteCandidateId { get; set; }
        public int MinuiteId { get; set; }
        public int EmployeeId { get; set; }
        public string ProposedBillet { get; set; }
        public string Remarks1 { get; set; }
        public string Remarks2 { get; set; }
        public string Remarks3 { get; set; }
        public Nullable<int> Remarks4 { get; set; }
        public Nullable<int> Remarks5 { get; set; }
        public Nullable<int> Remarks6 { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual DashBoardMinuite100 DashBoardMinuite100 { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
