//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashBoardMinuite100
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DashBoardMinuite100()
        {
            this.DashBoardMinuite110 = new HashSet<DashBoardMinuite110>();
        }
    
        public int MinuiteId { get; set; }
        public string MinuiteNo { get; set; }
        public string NextMinuiteNo { get; set; }
        public Nullable<int> MinuiteCategory { get; set; }
        public string MinuiteName { get; set; }
        public string LetterNo { get; set; }
        public string OfferedBy { get; set; }
        public Nullable<int> Vacency { get; set; }
        public Nullable<int> Nominate { get; set; }
        public string Purpose { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Location { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string RankName { get; set; }
        public string BranchName { get; set; }
        public string officerRankof { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> MinuiteDate { get; set; }
        public string PreRequQul { get; set; }
        public string Remarks { get; set; }
        public string ServiceExperiance { get; set; }
        public string Competencies { get; set; }
        public string ExtraRemarks1 { get; set; }
        public string ExtraRemarks2 { get; set; }
        public string ExtraRemarks3 { get; set; }
        public string ExtraRemarks4 { get; set; }
        public string ExtraRemarks5 { get; set; }
        public Nullable<int> ExtraRemarks6 { get; set; }
        public Nullable<int> ExtraRemarks7 { get; set; }
        public Nullable<int> ExtraRemarks8 { get; set; }
        public Nullable<int> ExtraRemarks9 { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashBoardMinuite110> DashBoardMinuite110 { get; set; }
    }
}
