//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashBoardMinuteStandby975
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> RankId { get; set; }
        public System.DateTime DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string StandbyRemarks1 { get; set; }
        public string StandbyRemarks2 { get; set; }
        public string StandbyRemarks3 { get; set; }
        public string StandbyRemarks4 { get; set; }
        public string StandbyRemarks5 { get; set; }
        public Nullable<int> StandbyRemarks6 { get; set; }
        public Nullable<int> StandbyRemarks7 { get; set; }
        public Nullable<int> StandbyRemarks8 { get; set; }
        public Nullable<int> StandbyRemarks9 { get; set; }
        public Nullable<int> StandbyRemarks10 { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Rank Rank { get; set; }
    }
}
