//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationPreviou
    {
        public int EducationId { get; set; }
        public int EmployeeId { get; set; }
        public int ExaminationId { get; set; }
        public int PassingYear { get; set; }
        public int ExamSubjectId { get; set; }
        public int InistitudeId { get; set; }
        public int ResultTypeId { get; set; }
        public double Gpa { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Modified { get; set; }
        public string ModifiedBy { get; set; }
        public bool Active { get; set; }
    
        public virtual ResultType ResultType { get; set; }
    }
}
