//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public long EducationId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> ExamCategoryId { get; set; }
        public Nullable<int> ExaminationId { get; set; }
        public Nullable<int> BoardId { get; set; }
        public Nullable<long> InstituteId { get; set; }
        public Nullable<int> Subjectid { get; set; }
        public string Roll { get; set; }
        public string RegNo { get; set; }
        public Nullable<int> ResultId { get; set; }
        public Nullable<int> ResultGradeId { get; set; }
        public Nullable<double> Gpa { get; set; }
        public Nullable<double> Marks { get; set; }
        public string Distiction { get; set; }
        public string PassingYear { get; set; }
        public string CourseDuration { get; set; }
        public string OtherInstituteName { get; set; }
        public string OtherSubjectName { get; set; }
        public System.DateTime ResultPublishDate { get; set; }
        public string FileName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ResultText { get; set; }
        public Nullable<double> Percentage { get; set; }
        public bool IsVarified { get; set; }
    
        public virtual Board Board { get; set; }
        public virtual ExamCategory ExamCategory { get; set; }
        public virtual Examination Examination { get; set; }
        public virtual Institute Institute { get; set; }
        public virtual Result Result { get; set; }
        public virtual ResultGrade ResultGrade { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
