//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSecurityClearance
    {
        public int EmployeeSecurityClearanceId { get; set; }
        public int EmployeeId { get; set; }
        public bool IsBackLog { get; set; }
        public Nullable<int> RankId { get; set; }
        public Nullable<int> TransferId { get; set; }
        public System.DateTime ClearanceDate { get; set; }
        public Nullable<System.DateTime> Expirydate { get; set; }
        public int SecurityClearanceReasonId { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> IsCleared { get; set; }
        public string NotClearReason { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Rank Rank { get; set; }
        public virtual SecurityClearanceReason SecurityClearanceReason { get; set; }
        public virtual Transfer Transfer { get; set; }
    }
}
