//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMscEducation
    {
        public int EmployeeMscEducationId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> RankId { get; set; }
        public Nullable<int> MscEducationTypeId { get; set; }
        public Nullable<int> MscInstituteId { get; set; }
        public Nullable<int> MscPermissionTypeId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string PassingYear { get; set; }
        public string Results { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string PermissionYear { get; set; }
        public Nullable<int> CompleteStatus { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual MscEducationType MscEducationType { get; set; }
        public virtual MscInstitute MscInstitute { get; set; }
        public virtual MscPermissionType MscPermissionType { get; set; }
        public virtual Rank Rank { get; set; }
    }
}
