//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeChildren
    {
        public int EmployeeChildrenId { get; set; }
        public int EmployeeId { get; set; }
        public int ChildrenType { get; set; }
        public Nullable<int> Child { get; set; }
        public string Name { get; set; }
        public string NameBan { get; set; }
        public string FileName { get; set; }
        public string GenFormName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string LivingWith { get; set; }
        public string ContactAddress { get; set; }
        public Nullable<int> OccupationId { get; set; }
        public string OfficeAddress { get; set; }
        public bool IsDead { get; set; }
        public Nullable<System.DateTime> DeadDate { get; set; }
        public string DeadReason { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> GoldenChild { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Occupation Occupation { get; set; }
    }
}
