//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeGeneral
    {
        public int EmployeeGeneralId { get; set; }
        public int EmployeeId { get; set; }
        public string ShortName { get; set; }
        public string ShortNameBan { get; set; }
        public string NickName { get; set; }
        public string NickNameBan { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public int CommissionTypeId { get; set; }
        public int BranchId { get; set; }
        public Nullable<int> SubBranchId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public string ContactNo { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> SeniorityDate { get; set; }
        public Nullable<System.DateTime> LieutenantDate { get; set; }
        public System.DateTime DoB { get; set; }
        public string BirthPlace { get; set; }
        public string BirthCerNo { get; set; }
        public Nullable<int> MaritalTypeId { get; set; }
        public Nullable<System.DateTime> MarriageDate { get; set; }
        public Nullable<int> OfficerStreamId { get; set; }
        public Nullable<int> NationalityId { get; set; }
        public Nullable<int> ReligionId { get; set; }
        public Nullable<int> ReligionCastId { get; set; }
        public bool IsBirthOutside { get; set; }
        public Nullable<System.DateTime> MigrationDate { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public string MigrationReason { get; set; }
        public Nullable<System.DateTime> CommissionDate { get; set; }
        public bool IsDead { get; set; }
        public Nullable<System.DateTime> DeadDate { get; set; }
        public Nullable<System.DateTime> AgeLimit { get; set; }
        public Nullable<System.DateTime> ServiceLimit { get; set; }
        public Nullable<System.DateTime> LastRLAvailedDate { get; set; }
        public Nullable<System.DateTime> LprDate { get; set; }
        public Nullable<System.DateTime> RetireDate { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public bool IsContract { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public string DeadReason { get; set; }
        public Nullable<int> SasbStatus { get; set; }
        public string SasbRemarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Category Category { get; set; }
        public virtual CommissionType CommissionType { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual MaritalType MaritalType { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual OfficerStream OfficerStream { get; set; }
        public virtual Religion Religion { get; set; }
        public virtual ReligionCast ReligionCast { get; set; }
        public virtual SubBranch SubBranch { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
