//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCourseFuturePlan
    {
        public int EmployeeCoursePlanId { get; set; }
        public int EmployeeId { get; set; }
        public int CourseCategoryId { get; set; }
        public Nullable<int> CourseSubCategoryId { get; set; }
        public Nullable<int> CoureseId { get; set; }
        public bool IsMandatory { get; set; }
        public Nullable<System.DateTime> PlanDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual CourseCategory CourseCategory { get; set; }
        public virtual CourseSubCategory CourseSubCategory { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
