//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCarLoan
    {
        public int EmployeeCarLoanId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsBackLog { get; set; }
        public Nullable<int> RankId { get; set; }
        public Nullable<int> CarLoanFiscalYearId { get; set; }
        public Nullable<System.DateTime> AvailDate { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Remarks { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public bool Active { get; set; }
    
        public virtual CarLoanFiscalYear CarLoanFiscalYear { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Rank Rank { get; set; }
    }
}
