//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePromotion
    {
        public int EmployeePromotionId { get; set; }
        public int EmployeeId { get; set; }
        public int PromotionBoardId { get; set; }
        public int FromRankId { get; set; }
        public int ToRankId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ExecutionDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public bool ExType { get; set; }
        public Nullable<int> BoardRemarkId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
