//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraAppointment
    {
        public int ExtraAppointmentId { get; set; }
        public Nullable<int> TransferId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> AppointmentId { get; set; }
        public int OfficeId { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ExtAptCd { get; set; }
        public Nullable<int> TYear { get; set; }
        public Nullable<int> Transcd { get; set; }
    
        public virtual Transfer Transfer { get; set; }
        public virtual OfficeAppointment OfficeAppointment { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Office Office { get; set; }
    }
}
