//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeavePolicy
    {
        public int LeavePolicyId { get; set; }
        public int CommissionTypeId { get; set; }
        public int LeaveTypeId { get; set; }
        public int LeaveDuration { get; set; }
        public string LeaveDurationType { get; set; }
        public Nullable<int> Slot { get; set; }
        public Nullable<int> ForeignDuration { get; set; }
        public string ForeignDurationType { get; set; }
        public Nullable<int> TmYear { get; set; }
        public string WATP { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual CommissionType CommissionType { get; set; }
        public virtual LeaveType LeaveType { get; set; }
    }
}
