//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedalAward
    {
        public int MedalAwardId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> MedalId { get; set; }
        public Nullable<int> AwardId { get; set; }
        public Nullable<int> PublicationId { get; set; }
        public Nullable<int> PublicationCategoryId { get; set; }
        public Nullable<int> Type { get; set; }
        public bool IsBackLog { get; set; }
        public Nullable<int> RankId { get; set; }
        public Nullable<int> TransferId { get; set; }
        public System.DateTime Date { get; set; }
        public string Remarks { get; set; }
        public string FileName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> BOffCd { get; set; }
        public Nullable<int> AOffCd { get; set; }
    
        public virtual Award Award { get; set; }
        public virtual Medal Medal { get; set; }
        public virtual Publication Publication { get; set; }
        public virtual PublicationCategory PublicationCategory { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
