//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeShipment
    {
        public int OfficeMoveId { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public Nullable<int> PreviousParentId { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<int> PreZoneId { get; set; }
        public Nullable<int> PreAdminAuthorityId { get; set; }
        public string PreAddress { get; set; }
    }
}
