//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OprAptSuitability
    {
        public int Id { get; set; }
        public int EmployeeOprId { get; set; }
        public int SpecialAptTypeId { get; set; }
        public int SuitabilityId { get; set; }
        public string Note { get; set; }
    
        public virtual SpecialAptType SpecialAptType { get; set; }
        public virtual Suitability Suitability { get; set; }
        public virtual EmployeeOpr EmployeeOpr { get; set; }
    }
}
