//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreCommissionCourse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PreCommissionCourse()
        {
            this.PreCommissionCourseDetail = new HashSet<PreCommissionCourseDetail>();
        }
    
        public long PreCommissionCourseId { get; set; }
        public int EmployeeId { get; set; }
        public string BnaNo { get; set; }
        public bool IsAbroad { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> MedalId { get; set; }
        public string Punishment { get; set; }
        public string AppointmentHeld { get; set; }
        public Nullable<double> ModuleD { get; set; }
        public Nullable<double> Total { get; set; }
        public string FinalPosition { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Medal Medal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreCommissionCourseDetail> PreCommissionCourseDetail { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
