//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreCommissionCourseDetail
    {
        public int PreCommissionCourseDetailId { get; set; }
        public long PreCommissionCourseId { get; set; }
        public string ModuleName { get; set; }
        public string OutOfMark { get; set; }
        public string AchievedMark { get; set; }
        public string Position { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual PreCommissionCourse PreCommissionCourse { get; set; }
    }
}
