//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PunishmentAccident
    {
        public int PunishmentAccidentId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> PunishmentCategoryId { get; set; }
        public Nullable<int> PunishmentSubCategoryId { get; set; }
        public Nullable<int> PunishmentNatureId { get; set; }
        public bool IsBackLog { get; set; }
        public Nullable<int> RankId { get; set; }
        public Nullable<int> TransferId { get; set; }
        public int Type { get; set; }
        public Nullable<int> AccedentType { get; set; }
        public Nullable<int> DurationMonths { get; set; }
        public Nullable<int> DurationDays { get; set; }
        public System.DateTime Date { get; set; }
        public string PunishmentType { get; set; }
        public string Reason { get; set; }
        public string Remarks { get; set; }
        public double PunishmentValue { get; set; }
        public double SkipYear { get; set; }
        public double DeductPercentage { get; set; }
        public int DeductYear { get; set; }
        public double PtAfterDeduct { get; set; }
        public int YearCount { get; set; }
        public bool IsProcessed { get; set; }
        public string FileName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual PunishmentCategory PunishmentCategory { get; set; }
        public virtual PunishmentNature PunishmentNature { get; set; }
        public virtual PunishmentSubCategory PunishmentSubCategory { get; set; }
        public virtual Rank Rank { get; set; }
    }
}
