//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetiredAge
    {
        public int RetiredAgeId { get; set; }
        public int CategoryId { get; set; }
        public int SubCategoryId { get; set; }
        public int RankId { get; set; }
        public int AgeLimit { get; set; }
        public int RStatus { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual SubCategory SubCategory { get; set; }
        public virtual Rank Rank { get; set; }
        public virtual Category Category { get; set; }
    }
}
