//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetiredEmpCertificate
    {
        public int RetiredEmpCertificateId { get; set; }
        public int RetiredEmployeeId { get; set; }
        public int CertificateId { get; set; }
    
        public virtual Certificate Certificate { get; set; }
        public virtual RetiredEmployee RetiredEmployee { get; set; }
    }
}
