//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetiredEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RetiredEmployee()
        {
            this.RetiredEmpCertificate = new HashSet<RetiredEmpCertificate>();
            this.RetiredEmpCountry = new HashSet<RetiredEmpCountry>();
        }
    
        public int RetiredEmployeeId { get; set; }
        public int EmployeeId { get; set; }
        public string TsNo { get; set; }
        public bool IsVisitAbroad { get; set; }
        public bool IsJobAbroad { get; set; }
        public bool IsPensionIssued { get; set; }
        public string BookNo { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RetiredEmpCertificate> RetiredEmpCertificate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RetiredEmpCountry> RetiredEmpCountry { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
