//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinity.Bnois.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingResult
    {
        public int TrainingResultId { get; set; }
        public Nullable<int> CourseCategoryId { get; set; }
        public Nullable<int> CourseSubCategoryId { get; set; }
        public int TrainingPlanId { get; set; }
        public int EmployeeId { get; set; }
        public int ResultTypeId { get; set; }
        public Nullable<System.DateTime> ResultDate { get; set; }
        public Nullable<double> Percentage { get; set; }
        public Nullable<int> Positon { get; set; }
        public Nullable<int> ResultStatus { get; set; }
        public string FileName { get; set; }
        public string ResultSection { get; set; }
        public string Remarks { get; set; }
        public string Unit { get; set; }
        public string DsRecom { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CId { get; set; }
    
        public virtual CourseCategory CourseCategory { get; set; }
        public virtual CourseSubCategory CourseSubCategory { get; set; }
        public virtual ResultType ResultType { get; set; }
        public virtual TrainingPlan TrainingPlan { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
