// <auto-generated />
namespace Infinity.Bnois.Configuration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ConfigurationDbContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConfigurationDbContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201809140822183_ConfigurationDbContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
